name: Package Build and Tests

on:
  pull_request:
    branches:
      -main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash -el {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: my-env
          environment-file: env.yml
          auto-activate-base: false

      - name: Run Flake8
        run: flake8 src/Python_package/nonstandardcode.py

      - name: Run nonstandardcode.py
        run: |
          pwd
          python src/Python_package/nonstandardcode.py
